feat: metadata import
agritheory/shipstation_integration pull request #17
Opened 2024-05-28 11:57 UTC by Alchez

Porting (with squash) https://github.com/ParsimonyGit/shipstation_integration/pull/80 to v15.

2024-05-28 12:35 UTC, agritheory requested changes

2024-05-28 12:35 UTC, agritheory commented on shipstation_integration/customer.py
>  def overwrite_validate_phone_number(data, throw=False):
`overwrite` => `override`

2024-05-28 12:35 UTC, agritheory commented on shipstation_integration/orders.py
> +			"uom": frappe.db.get_single_value("Stock Settings", "stock_uom"),
This should happen in the `create_item` step, and use the Item's Stock UOM here.

2024-05-28 12:35 UTC, agritheory commented on shipstation_integration/shipstation_integration/doctype/shipstation_item_custom_field/shipstation_item_custom_field.py
> +# Copyright (c) 2023, Parsimony LLC and contributors
Copyright is wrong

2024-05-30 05:50 UTC, Alchez commented
@agritheory A lot of the changes here depend on #16. I think that one can be merged before this for a better review.

2024-11-14 22:31 UTC, batonac commented
hey @Alchez anything I can do to push this one along?

2024-11-15 05:29 UTC, Alchez commented
Hey @batonac, can you look at the merge conflicts for this one. I haven't looked at this one in a while, but I can give it another review

2026-07-02 20:04 UTC, batonac commented
closing as we're moving forward with a hook-based solution

2026-07-02 20:04 UTC, closed without merging